language: android
dist: trusty
android:
  components:
    - platform-tools
    # The BuildTools version used by your project
    - build-tools-29.0.3
    # The SDK version used to compile your project
    - android-29
    - extra-google-m2repository
    - extra-android-m2repository
    
branches:
  only:
  
  - /.*/
  
script:
chmod +x gradlew
- ./gradlew clean test assembleDebug
